Simplification of the Button component
poop-team/daydream pull request #60
Opened 2022-10-30 21:02 UTC by kitorer

Changes:
  props extends pressable props so now we can use any of those methods and not just OnPress,
  ClassName is for additional styles and that is optional,
  Children changed to optional, sometimes you only want to pass in text which can be done with `name = "name"`
  Children changed from from ReactNode[] to ReactNode, its just simpler this way to keeping it to one component being passed in.
Bugfix:
  adding back the space to the end of the baseStyle string because that string does get modified

2022-10-30 22:07 UTC, Rikimbili requested changes

2022-10-30 22:07 UTC, Rikimbili commented on mobile/src/components/Button.tsx
> +    console.log(baseStyle);
Don't forget to remove debugging console logs

2022-10-30 22:07 UTC, Rikimbili commented on mobile/src/components/Button.tsx
> +  let baseStyle = "h-7 items-center justify-center ";
I recommend you add the spacing in front wherever you append more styles instead of at the end like this.

2022-10-31 15:45 UTC, rob-3 approved these changes

2022-10-31 15:58 UTC, Rikimbili approved these changes

2022-10-31 16:04 UTC, merged