Feat mobile authj wireup
poop-team/daydream pull request #86
Opened 2022-11-07 21:35 UTC by kitorer

I just need to test this and I will PR this up

2022-11-08 15:03 UTC, kitorer commented on mobile/App.tsx
> +        <Stack.Screen
this page will eventually be refactored with a auth flow in mind [[](https://reactnavigation.org/docs/auth-flow)](https://reactnavigation.org/docs/auth-flow)

2022-11-08 15:03 UTC, kitorer commented on mobile/src/pages/Login.tsx
> +      <View className="flex-1 w-full items-center position-relative justify-center">
api wireup changes start below, sorry rest is prettier

2022-11-08 15:03 UTC, kitorer commented on mobile/src/pages/Register.tsx
> +          <Pressable>
api wireup changes start below

2022-11-08 17:09 UTC, rob-3 requested changes

2022-11-09 03:53 UTC, rob-3 approved these changes

2022-11-09 03:53 UTC, rob-3 commented on mobile/src/pages/Login.tsx
> +                    setIsPending(false);
I think this should go above `navigation.navigate()` because the component might be destroyed when that happens.

2022-11-09 04:15 UTC, merged