yarn workspaces
poop-team/daydream pull request #99
Opened 2022-11-10 18:29 UTC by rob-3

- Remove yarn files
- feat: initialize yarn workspaces as monorepo
- feat: add jsonwebtoken to common
- feat: add helpers into common/
- feat: add index.ts for export # Please enter the commit message for your changes. Lines starting
- refactor: move all utilities from web/
- fix: resolve a missing type
- fix: fix all web imports
- refactor: import types in mobile from @daydream/common
- fix: add typescript black magic to get the types to be right

2022-11-10 19:03 UTC, Rikimbili commented
I should have left turborepo on the project lol

2022-11-10 19:10 UTC, rob-3 commented
When I was about 80% done with this I was thinking either that, or would've just been easier to copy-paste code. But I'm glad I figured out how to get it to (mostly) work on my own

2022-11-10 19:46 UTC, Rikimbili requested changes
One more thing:
- The utils/jwt and utils/validation file should only be on web as it is only used by the API and has next.js specific types

2022-11-10 19:46 UTC, Rikimbili commented on package.json
> +    "dev": "yarn workspace @daydream/web dev"
We might not need these scripts. We can just cd into the directory and run the correct project. Also not sure how yarn workspaces handles this way of running the project

2022-11-10 19:46 UTC, Rikimbili commented on common/package.json
> +		"typescript": "^4.8.4"
Some things here.
- This package doesnt use next and as such it shouldnt be specified here
- We are using next 12. Next 13 is technically the same but some imports would need to be fixed
- typescript should be a dev dependency

2022-11-10 19:46 UTC, Rikimbili commented on common/tsconfig.json
> +}
Why not use the same tsconfig we have in web?

2022-11-10 19:46 UTC, Rikimbili commented on mobile/package.json
> +    "@daydream/common": "1.0.0",
we could also include this as "@daydream/common": "workspace:^"

2022-11-10 19:46 UTC, Rikimbili commented on web/package.json
>      "react-hot-toast": "2.4.0",
Don't forget to add "@daydream/common": "workspace:^" on web too

2022-11-10 19:52 UTC, Rikimbili commented on common/index.ts
> +export * from "./helpers/request";
It might be a good idea to avoid this barrel import to keep the context of the directories when importing (/types, /helpers, /utils, etc)

2022-11-10 20:12 UTC, Rikimbili commented
Let me know once you comment/resolve these points I mentioned. I tried testing web locally but I'm getting a Module parse failed error btw

2022-11-10 20:13 UTC, Rikimbili commented on common/index.ts
> +export * from "./helpers/request";
Maybe do the barrel export inside of each subdirectory like the ones I mentioned

2022-11-12 02:50 UTC, rob-3 commented
Couldn't figure this out; closing as we've sunk 10+ collective hours into this already

2022-11-12 02:50 UTC, closed without merging